// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDkbMrrB0XKmUXuD0fJ12DlR0W_SVWbVX0',
    appId: '1:515934950704:web:36f72bba6c6b2b9e6f64f5',
    messagingSenderId: '515934950704',
    projectId: 'qcart-b5ab2',
    authDomain: 'qcart-b5ab2.firebaseapp.com',
    databaseURL: 'https://qcart-b5ab2-default-rtdb.firebaseio.com',
    storageBucket: 'qcart-b5ab2.firebasestorage.app',
    measurementId: 'G-J5DYJ433L5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDi_SJcJcFUQrBVJIpblq9s5CnYbugr5x0',
    appId: '1:515934950704:android:c2096df4d9e909226f64f5',
    messagingSenderId: '515934950704',
    projectId: 'qcart-b5ab2',
    databaseURL: 'https://qcart-b5ab2-default-rtdb.firebaseio.com',
    storageBucket: 'qcart-b5ab2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCE5m6JzqM6l-YKSnuXmijUcMQD3N6qgcY',
    appId: '1:515934950704:ios:8cb82d0aeb03799c6f64f5',
    messagingSenderId: '515934950704',
    projectId: 'qcart-b5ab2',
    databaseURL: 'https://qcart-b5ab2-default-rtdb.firebaseio.com',
    storageBucket: 'qcart-b5ab2.firebasestorage.app',
    iosBundleId: 'com.example.quicks',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCE5m6JzqM6l-YKSnuXmijUcMQD3N6qgcY',
    appId: '1:515934950704:ios:8cb82d0aeb03799c6f64f5',
    messagingSenderId: '515934950704',
    projectId: 'qcart-b5ab2',
    databaseURL: 'https://qcart-b5ab2-default-rtdb.firebaseio.com',
    storageBucket: 'qcart-b5ab2.firebasestorage.app',
    iosBundleId: 'com.example.quicks',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDVEfbF3A6oJJ2C-UbUunqQ0z3HSCnwvGE',
    appId: '1:515934950704:web:18ea57e34f0ec2ed6f64f5',
    messagingSenderId: '515934950704',
    projectId: 'qcart-b5ab2',
    authDomain: 'qcart-b5ab2.firebaseapp.com',
    databaseURL: 'https://qcart-b5ab2-default-rtdb.firebaseio.com',
    storageBucket: 'qcart-b5ab2.firebasestorage.app',
    measurementId: 'G-XWHN4ZX065',
  );
}
